<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
use O8\Core\Runtime;
use O8\Auth\{AuthService,BootstrapService};
use O8\Install\Migrator;
use O8\Admin\{Administration,TenantDeletion};
use O8\Storage\Storage;
use O8\Documents\Documents;
use O8\Documents\Evaluation;
use O8\Documents\TrashRetention;
if (PHP_SAPI!=='cli' || !preg_match('#^/tmp/o8-m2-test\.[A-Za-z0-9]+/db\.sock$#D',$argv[1]??'')) exit("Isolated test socket required.\n");
$db=new PDO('mysql:unix_socket='.$argv[1].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$test='storage_test_'.bin2hex(random_bytes(4)); $db->exec('CREATE DATABASE '.$test); $db->exec('USE '.$test);
$tmp=dirname($argv[1]).'/'.$test; mkdir($tmp); mkdir($tmp.'/files');
$root=dirname(__DIR__); $runtime=new Runtime($tmp.'/system'); $identity=$runtime->identity(); $m=new Migrator($db,$root.'/database/migrations'); $m->install($identity); $m->upgrade($identity);
$auth=new AuthService($db,$runtime,$identity['key']); $admin=new Administration($db); $storage=new Storage($db,$root); $docs=new Documents($db,$root); $checks=0;
function check(bool $ok,string $label):void { global $checks; if (!$ok) throw new RuntimeException('FAIL '.$label); ++$checks; echo "PASS $label\n"; }
function rejects(callable $fn,string $label):void { try { $fn(); } catch (RuntimeException|InvalidArgumentException $e) { check(true,$label); return; } check(false,$label); }
function sql(string $q,array $p=[]):PDOStatement { global $db; $s=$db->prepare($q); $s->execute($p); return $s; }
check((int)sql("SELECT COUNT(DISTINCT index_name) FROM information_schema.statistics WHERE table_schema=DATABASE() AND index_name IN ('documents_search_latest','documents_owner_search_latest','invoice_gross_document','accounting_account_code','invoice_item_account_document')")->fetchColumn()===5,'search index migration is applied');
$session=$auth->login('operator','admin','owndms8','test',$runtime->issueSetupToken()); $session=$auth->changePassword($auth->actor($session),'owndms8','operator-secret');
$uuid=(new BootstrapService($db))->complete($auth->actor($session),'Admin','admin@example.test','Alpha'); $op=$auth->actor($session);
$aSession=$auth->login('account','admin','operator-secret','test'); $a=$auth->actor($aSession);
$second=$admin->createTenant($op,'Beta','',['login'=>'beta','name'=>'Beta','email'=>'beta@example.test','password'=>'secret6']);
$bSession=$auth->login('account','beta','secret6','test'); $bSession=$auth->changePassword($auth->actor($bSession),'secret6','beta-secret'); $b=$auth->actor($bSession);
$uid=$admin->createUser($a,['login'=>'user','name'=>'User','email'=>'user@example.test','password'=>'secret6'],'user');
$uSession=$auth->login('account','user','secret6','test'); $uSession=$auth->changePassword($auth->actor($uSession),'secret6','user-secret'); $u=$auth->actor($uSession);
$third=$admin->createTenant($op,'Gamma','',['login'=>'gamma','name'=>'Gamma','email'=>'gamma@example.test','password'=>'secret6']);
$gamma=(int)sql('SELECT id FROM tenants WHERE public_id=?',[$third])->fetchColumn();
check($auth->sessionMinutes($a->tenantId())===480 && $auth->sessionMinutes($b->tenantId())===480,'tenant sessions default to eight hours');
rejects(fn()=>$auth->saveSessionMinutes($u,'15'),'normal user cannot change tenant session duration');
rejects(fn()=>$auth->saveSessionMinutes($a,'0'),'session duration rejects invalid values');
$auth->saveSessionMinutes($a,'15');
check($auth->sessionMinutes($a->tenantId())===15 && $auth->sessionMinutes($b->tenantId())===480,'session setting is tenant-isolated');
$expiredSession=$aSession; $expiredSession['last_activity']=time()-901;
check($auth->actor($expiredSession)===null && $auth->actor($aSession)?->kind==='tenant','tenant idle timeout is enforced by authentication');
$auth->saveSessionMinutes($a,'480');
$owner=posix_getpwuid(posix_geteuid())['name']; $group=posix_getgrgid(posix_getegid())['name'];
rejects(fn()=>$storage->configure($a,$a->tenantId(),$tmp.'/files',$owner,$group),'tenant admin cannot assign arbitrary server paths');
rejects(fn()=>$storage->configure($op,$a->tenantId(),'/tmp',$owner,$group),'broad shared directory rejected');
rejects(fn()=>$storage->configure($op,$a->tenantId(),$root.'/storage',$owner,$group),'project storage rejected');
symlink($tmp.'/files',$tmp.'/alias');
rejects(fn()=>$storage->configure($op,$a->tenantId(),$tmp.'/alias',$owner,$group),'symlink base rejected');
rejects(fn()=>$storage->configure($op,$a->tenantId(),$tmp.'/files','o8_nonexistent_user_999',$group),'unknown Linux user rejected');
mkdir($tmp.'/files/'.$uuid); file_put_contents($tmp.'/files/'.$uuid.'/keep','unmanaged');
rejects(fn()=>$storage->configure($op,$a->tenantId(),$tmp.'/files',$owner,$group),'preexisting unmanaged tenant directory rejected');
check(file_get_contents($tmp.'/files/'.$uuid.'/keep')==='unmanaged','unmanaged files untouched');
rename($tmp.'/files/'.$uuid,$tmp.'/unmanaged-preserved');
$storage->configure($op,$a->tenantId(),$tmp.'/files',$owner,$group);
$location=$storage->location($a); [$base,$target]=$storage->paths($location);
check($target===$tmp.'/files/'.$uuid,'UUID scoped directory assigned');
check((fileperms($target)&0777)===0750 && (fileperms($target.'/.o8-storage')&0777)===0640,'private directory and marker modes');
check(count(glob($target.'/.probe-*'))===0,'probe files removed after success');
$storage->configure($op,$a->tenantId(),$tmp.'/files',$owner,$group);
mkdir($tmp.'/smb-compatible');
$storage->configure($op,$gamma,$tmp.'/smb-compatible','o8_smb_owner','o8_smb_group',false);
$compat=sql("SELECT s.*,t.public_id FROM storage_locations s JOIN tenants t ON t.id=s.tenant_id WHERE s.tenant_id=? AND s.storage_key='main'",[$gamma])->fetch();
check((int)$compat['enforce_file_attributes']===0 && $storage->paths($compat)[1]===$tmp.'/smb-compatible/'.$third,'SMB compatibility keeps identity and functional checks without POSIX attribute enforcement');
check(count($storage->locations($op))===3,'operator storage listing includes configured and unconfigured tenants');
$storage->configure($op,$b->tenantId(),$tmp.'/files',$owner,$group);
$foreign=$storage->location($b);
rename($tmp.'/files',$tmp.'/held'); mkdir($tmp.'/files');
rejects(fn()=>$storage->paths($location),'missing/replaced mount fails closed');
rmdir($tmp.'/files'); rename($tmp.'/held',$tmp.'/files');
rename($target.'/.o8-storage',$target.'/.marker-held'); symlink($target.'/.marker-held',$target.'/.o8-storage');
rejects(fn()=>$storage->paths($location),'marker symlink fails closed');
unlink($target.'/.o8-storage'); rename($target.'/.marker-held',$target.'/.o8-storage');
mkdir($tmp.'/different');
rejects(fn()=>$storage->configure($op,$a->tenantId(),$tmp.'/different',$owner,$group),'configured root cannot silently move');
file_put_contents($tmp.'/sample.pdf',"%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\ntrailer\n<< /Root 1 0 R >>\n%%EOF\n");
file_put_contents($tmp.'/attack.pdf','<html><script>alert(1)</script></html>');
file_put_contents($tmp.'/note.txt',"Plain text document\n");
file_put_contents($tmp.'/binary.txt',"text\0binary");
$odt=new ZipArchive(); check($odt->open($tmp.'/note.odt',ZipArchive::CREATE|ZipArchive::OVERWRITE)===true,'ODT fixture can be created'); $odt->addFromString('mimetype','application/vnd.oasis.opendocument.text'); $odt->setCompressionName('mimetype',ZipArchive::CM_STORE); $odt->addFromString('content.xml','<office:document-content/>'); $odt->close();
rejects(fn()=>$docs->ingest($a,$tmp.'/attack.pdf','attack.pdf'),'HTML masquerading as PDF rejected');
rejects(fn()=>$docs->ingest($a,$tmp.'/binary.txt','binary.txt'),'binary data masquerading as TXT rejected');
rejects(fn()=>$docs->upload($a,['tmp_name'=>$tmp.'/sample.pdf','name'=>'sample.pdf','error'=>0]),'HTTP upload cannot accept a local file path');
rejects(fn()=>$docs->ingest($op,$tmp.'/sample.pdf','sample.pdf'),'operator cannot ingest documents');
$id=$docs->ingest($a,$tmp.'/sample.pdf','../../Invoice <safe>.pdf'); $doc=$docs->get($a,$id);
check((int)$doc['in_inbox']===1 && (int)$doc['owner_id']===$a->id(),'upload enters inbox with authenticated membership owner');
check($doc['original_name']==='Invoice <safe>.pdf','original name has no path components');
$file=sql("SELECT * FROM document_files WHERE document_id=?",[$id])->fetch();
check(preg_match('/^[a-f0-9]{48}\.pdf$/D',$file['relative_path'])===1,'random server filename independent of client');
check(hash_file('sha256',$target.'/'.$file['relative_path'])===$file['sha256'],'stored checksum matches original');
check((fileperms($target.'/'.$file['relative_path'])&0777)===0640,'uploaded original has private mode');
rejects(fn()=>$storage->relocate($a,$a->tenantId(),$tmp.'/different'),'tenant admin cannot change storage path');
rejects(fn()=>$storage->relocate($op,$a->tenantId(),$tmp.'/different'),'missing target cannot be rebound');
check($storage->location($a)['root_path']===$tmp.'/files','failed rebind retains original database path');
rename($target,$tmp.'/different/'.$uuid);
// The marker must stay unchanged even if the directory has been moved.
$moved=$tmp.'/different/'.$uuid;
$originalMarker=file_get_contents($moved.'/.o8-storage');
file_put_contents($moved.'/.o8-storage',str_repeat('0',64));
rejects(fn()=>$storage->relocate($op,$a->tenantId(),$tmp.'/different'),'changed marker prevents rebind');
file_put_contents($moved.'/.o8-storage',$originalMarker);
// A copied file of the expected size is required at the new location.
rename($moved.'/'.$file['relative_path'],$moved.'/'.$file['relative_path'].'.held');
rejects(fn()=>$storage->relocate($op,$a->tenantId(),$tmp.'/different'),'missing document prevents rebind');
rename($moved.'/'.$file['relative_path'].'.held',$moved.'/'.$file['relative_path']);
$storage->relocate($op,$a->tenantId(),$tmp.'/different');
$location=$storage->location($a); [$newBase,$target]=$storage->paths($location);
check($newBase===$tmp.'/different' && hash_file('sha256',$target.'/'.$file['relative_path'])===$file['sha256'],'operator rebind keeps original document and marker');
check($storage->paths($foreign)[1]===$tmp.'/files/'.$second,'other tenant remains on its original path');
rejects(fn()=>$storage->relocate($op,$b->tenantId(),$tmp.'/different'),'foreign tenant cannot use another tenant directory');
check($docs->listing($a,['scope'=>'inbox'])['total']===1 && $docs->listing($a,['scope'=>'all'])['total']===0,'inbox separate from all documents');
rejects(fn()=>$docs->get($b,$id),'foreign tenant cannot read metadata');
rejects(fn()=>$docs->open($b,$id),'foreign tenant cannot download');
rejects(fn()=>$docs->get($u,$id),'user cannot read another owner');
check($docs->listing($u,['scope'=>'inbox'])['total']===0,'user list does not leak another owner counts');
$own=$docs->ingest($u,$tmp.'/sample.pdf','Own.pdf');
check($docs->listing($u,['scope'=>'inbox'])['total']===1,'user sees own upload');
$ownRow=$docs->get($u,$own); $docs->status($u,$own,(int)$ownRow['revision'],'trash');
check($docs->trashCount($u)===1 && $docs->trashCount($a)===1 && $docs->trashCount($b)===0,'trash counts respect tenant and owner boundaries');
$ownRow=$docs->get($u,$own); $docs->status($u,$own,(int)$ownRow['revision'],'restore');
check($docs->trashCount($u)===0 && $docs->trashCount($a)===0,'restoring a document updates trash counts');
check($docs->listing($a,['scope'=>'inbox'])['total']===2,'admin sees own tenant documents');
rejects(fn()=>$docs->listing($u,['owner'=>$a->id()]),'user cannot request admin owner filter');
$admin->inviteUser($a,'user'); // Ensure schema additions coexist with purge plan.
$docs->createTag($a,'Invoice'); $tag=(int)$docs->tags($a)[0]['id'];
$docs->createTag($u,'User category'); check((int)sql('SELECT COUNT(*) FROM tags WHERE tenant_id=? AND normalized_name=?',[$a->tenantId(),'user category'])->fetchColumn()===1,'normal user can add a tenant catalogue tag');
$docs->createTag($b,'Foreign'); $foreignTag=(int)$docs->tags($b)[0]['id'];
rejects(fn()=>$docs->save($a,$id,1,['title'=>'Title','tags'=>[$foreignTag]]),'foreign tenant tag rejected');
$docs->save($a,$id,1,['title'=>'Saved invoice','sender'=>'Supplier','date'=>'2026-09-17','tags'=>[$tag],'memo'=>'literal % _']);
check($docs->listing($a,['scope'=>'all','query'=>'Saved','tag'=>(string)$tag])['total']===1,'metadata save accepts inbox and searchable tag filter');
check($docs->unfiledCount($a)===1 && $docs->unfiledCount($u)===0 && $docs->unfiledCount($b)===0,'unfiled counter excludes inbox and respects owner/tenant');
check($docs->listing($a,['scope'=>'all','query'=>'D'.$id,'folderCounts'=>'1'])['unfiledCount']===1,'global filtered unfiled counter includes unlinked match');
check($docs->listing($a,['scope'=>'all','query'=>'absent-token','folderCounts'=>'1'])['unfiledCount']===0,'unfiled counter clears when search has no matches');
check($docs->listing($a,['scope'=>'all','resultView'=>'latest','latestCount'=>'1','folderCounts'=>'1'])['unfiledCount']===1,'unfiled counter supports latest-N');
check($docs->listing($a,['scope'=>'all','query'=>'% _'])['total']===1,'metadata search treats wildcards literally');
check($docs->listing($a,['scope'=>'all','query'=>'D'.$id])['total']===1,'exact document ID search');
check($docs->listing($a,['scope'=>'all','query'=>'D'.$id,'folderCounts'=>'1'])['folderCounts']===[],'filtered folder count is available before folders exist');
check($docs->listing($a,['scope'=>'all','query'=>'D'.$id.' Supplier Invoice'])['total']===1,'wordwise AND across exact ID and metadata');
check($docs->listing($a,['scope'=>'all','query'=>'safe'])['total']===1,'original filename participates in search');
check($docs->listing($a,['scope'=>'all','resultView'=>'latest','latestCount'=>'1'])['total']===1,'latest-N result view limits the search set');
check($docs->listing($a,['scope'=>'all','resultView'=>'latest','latestCount'=>'1','folderCounts'=>'1'])['folderCounts']===[],'latest-N folder counts use the limited result set');
$ai=json_encode(['analysis'=>'machine-parity-token'],JSON_THROW_ON_ERROR);
sql('UPDATE documents SET search_text=?,ai_data=? WHERE tenant_id=? AND id=?',['indexed-parity-token',$ai,$a->tenantId(),$id]);
sql("INSERT INTO document_invoices (tenant_id,document_id,sender,invoice_number,invoice_date,entry_mode,currency,net,tax,gross) VALUES (?,?,? ,?,'2026-09-17','totals','EUR',100,19,119)",[$a->tenantId(),$id,'Supplier','INV-PARITY-42']);
check($docs->listing($a,['scope'=>'all','query'=>'machine-parity-token'])['total']===1 && $docs->listing($a,['scope'=>'all','query'=>'indexed-parity-token'])['total']===1,'global search includes retained AI data and search text');
check($docs->listing($a,['scope'=>'all','query'=>'INV-PARITY-42'])['total']===1,'global search includes structured invoice numbers');
$insertSearchDoc=static function(string $title,string $created) use($a): int { sql("INSERT INTO documents (tenant_id,owner_id,title,document_date,in_inbox,source_type,created_at) VALUES (?,? ,?,'2026-09-17',0,'test',?)",[$a->tenantId(),$a->id(),$title,$created]); global $db; return (int)$db->lastInsertId(); };
$olderNeedle=$insertSearchDoc('Needle older','2026-09-17 10:00:00');
$newerNeedle=$insertSearchDoc('Needle newer','2026-09-17 12:00:00');
$outsideLatest=$insertSearchDoc('Different later','2026-09-17 13:00:00');
$latestNeedle=$docs->listing($a,['scope'=>'all','query'=>'Needle','resultView'=>'latest','latestCount'=>'1','sort'=>'oldest']);
check($latestNeedle['total']===1 && $latestNeedle['matchingTotal']===2 && (int)$latestNeedle['rows'][0]['id']===$newerNeedle,'latest-N is applied after all search filters and reports both totals');
$combined=$docs->listing($a,['scope'=>'all','query'=>'Saved','dateFrom'=>'2026-09-17','dateTo'=>'2026-09-17','tag'=>(string)$tag,'owner'=>(string)$a->id(),'invoiceNumbers'=>'PARITY-42','amountFrom'=>'119','amountTo'=>'119']);
check($combined['total']===1 && (int)$combined['rows'][0]['id']===$id,'combined metadata, date, tag, owner, invoice number and amount filters intersect');
sql("INSERT INTO accounting_accounts (tenant_id,code,name) VALUES (?,'4980','Testkonto')",[$a->tenantId()]); $accountingAccount=(int)$db->lastInsertId();
$invoiceDoc=$docs->get($a,$olderNeedle);
$invoiceInput=['sender'=>'Buchungs-Absender','number'=>'BK-2026-1','date'=>'2026-09-17','mode'=>'items','currency'=>'EUR','accountId'=>(string)$accountingAccount,'items'=>[['description'=>'Leistung','quantity'=>'2','unitNet'=>'10.00','unitGross'=>'11.90','priceBasis'=>'net','accountId'=>'','vatRate'=>'19'],['description'=>'Ermäßigt','quantity'=>'1','unitNet'=>'5.00','unitGross'=>'5.35','priceBasis'=>'gross','accountId'=>(string)$accountingAccount,'vatRate'=>'7']],'taxes'=>[]];
$docs->saveInvoice($a,$olderNeedle,(int)$invoiceDoc['revision'],$invoiceInput);
$savedInvoice=$docs->get($a,$olderNeedle);
check((string)$docs->listing($a,['scope'=>'all','query'=>'D'.$olderNeedle])['rows'][0]['gross_amount']===(string)$savedInvoice['invoice']['gross'] && $docs->listing($a,['scope'=>'all','query'=>'D'.$olderNeedle])['rows'][0]['currency']==='EUR' && $docs->listing($a,['scope'=>'all','query'=>'D'.$newerNeedle])['rows'][0]['gross_amount']===null,'list exposes stored gross and currency only where booking data exists');
// DECIMAL(18,4) may return trailing zeros; assert the amount, not driver formatting.
check($savedInvoice['invoice']['number']==='BK-2026-1' && $savedInvoice['invoice']['mode']==='items' && count($savedInvoice['invoice']['items'])===2 && (float)$savedInvoice['invoice']['gross']===29.15,'invoice header, positions and computed totals persist');
$evaluation=new Evaluation($db); $period=['dateFrom'=>'2026-09-01','dateTo'=>'2026-09-30'];
$summary=$evaluation->bookingSummary($a,$period);
check(count($summary['months'])===1 && (int)$summary['months']['2026-09']['document_count']===2 && abs($summary['currencies']['EUR']['gross']-148.15)<0.001,'monthly evaluation returns stored EUR booking totals and document count');
check(abs($evaluation->bookingSummary($a,[])['currencies']['EUR']['gross']-148.15)<0.001,'evaluation needs neither date bound');
check(abs($evaluation->bookingSummary($a,['dateFrom'=>'2026-09-01'])['currencies']['EUR']['gross']-148.15)<0.001 && abs($evaluation->bookingSummary($a,['dateTo'=>'2026-09-30'])['currencies']['EUR']['gross']-148.15)<0.001,'evaluation accepts either date bound alone');
check(abs($evaluation->bookingSummary($a,$period+['accounts'=>[$accountingAccount]])['currencies']['EUR']['gross']-29.15)<0.001,'evaluation account filter selects only matching bookings');
check(abs($evaluation->bookingSummary($a,$period+['tag'=>$tag])['currencies']['EUR']['gross']-119)<0.001,'evaluation tag filter selects matching bookings');
check(abs($evaluation->bookingSummary($a,$period+['query'=>'D'.$id,'invoiceNumbers'=>'PARITY-42','amountFrom'=>'119','amountTo'=>'119'])['currencies']['EUR']['gross']-119)<0.001,'evaluation combines ID, invoice number and amount filters');
check(abs($evaluation->bookingSummary($a,$period+['query'=>'Needle','accountCode'=>'4980','documentType'=>'document','owner'=>(string)$a->id()])['currencies']['EUR']['gross']-29.15)<0.001,'evaluation combines text, account, type and owner filters');
check($evaluation->bookingSummary($a,$period+['resultView'=>'latest','latestCount'=>'1'])['selectedTotal']===1,'evaluation applies latest N after filters');
check($evaluation->bookingSummary($u,$period)['months']===[] && $evaluation->bookingSummary($b,$period)['months']===[],'evaluation respects owner and tenant scope');
rejects(fn()=>$evaluation->bookingSummary($a,array_replace($period,['dateTo'=>'2026-08-31'])),'evaluation rejects reversed date range');
check($docs->listing($a,['scope'=>'all','invoiceNumbers'=>'BK-2026-1','accountCode'=>'4980','amountFrom'=>'29.15','amountTo'=>'29.15'])['total']===1,'stored booking data participates in existing filters');
rejects(fn()=>$docs->saveInvoice($a,$olderNeedle,(int)$invoiceDoc['revision'],$invoiceInput),'stale revision cannot overwrite booking data');
$badInvoice=$invoiceInput; $badInvoice['items'][0]['vatRate']='5';
rejects(fn()=>$docs->saveInvoice($a,$newerNeedle,0,$badInvoice),'inactive VAT rate rejected server-side');
rejects(fn()=>$docs->saveInvoice($u,$olderNeedle,(int)$savedInvoice['revision'],$invoiceInput),'user cannot write another owner booking data');
rejects(fn()=>$docs->saveInvoice($b,$olderNeedle,(int)$savedInvoice['revision'],$invoiceInput),'foreign tenant cannot write booking data');
$docs->saveAccountingSettings($a,['framework'=>'SKR 03','vatRates'=>['7','19'],'accounts'=>[['code'=>'4980','name'=>'Testkonto geändert'],['code'=>'1200','name'=>'Bank']]]);
$accounting=$docs->accountingSettings($a);
check($accounting['framework']==='SKR 03' && count(array_filter($accounting['accounts'],fn($row)=>$row['active']))===2,'admin saves tenant accounting settings');
check(count($docs->accounting($a)['vatRates'])===2 && count($docs->accounting($a)['accounts'])===2,'booking editor receives active tenant accounting settings');
rejects(fn()=>$docs->saveAccountingSettings($a,['framework'=>'SKR 03','vatRates'=>['7'],'accounts'=>[['code'=>'4980','name'=>'Testkonto geändert']]]),'used VAT rate cannot be deactivated');
rejects(fn()=>$docs->saveAccountingSettings($u,['framework'=>'','vatRates'=>['19'],'accounts'=>[]]),'user cannot change tenant accounting settings');
check($docs->get($a,$olderNeedle)['invoice']===$savedInvoice['invoice'],'settings changes do not alter stored booking data');
rejects(fn()=>$docs->save($a,$id,1,['title'=>'Overwrite','tags'=>[]]),'stale revision cannot overwrite metadata');
rejects(fn()=>$docs->save($a,$id,2,['title'=>'Bad date','date'=>'2026-02-31','tags'=>[]]),'invalid date rejected');
$docs->folderWrite($a,'create',0,'Folder A'); $folder=(int)$docs->folders($a)[0]['id'];
$docs->folderWrite($a,'create',0,'Child A',$folder); $child=(int)array_values(array_filter($docs->folders($a),fn($row)=>(int)$row['parent_id']===$folder))[0]['id'];
rejects(fn()=>$docs->folderWrite($a,'create',0,'Child A',$folder),'duplicate sibling folder name rejected');
$docs->link($a,$id,2,$child,false);
check($docs->listing($a,['scope'=>(string)$folder])['total']===0 && $docs->listing($a,['scope'=>(string)$child])['total']===1,'parent excludes child documents');
$filtered=$docs->listing($a,['scope'=>'all','query'=>'D'.$id,'folderCounts'=>'1']);
check($filtered['total']===1 && ($filtered['folderCounts'][$folder]??-1)===0 && ($filtered['folderCounts'][$child]??0)===1,'search counts only directly linked folders');
check($filtered['unfiledCount']===0 && $docs->unfiledCount($a)===$docs->listing($a,['scope'=>'unfiled'])['total'],'linked document no longer contributes to unfiled counters');
$filtered=$docs->listing($a,['scope'=>'all','query'=>'Own','folderCounts'=>'1']);
check($filtered['total']===0 && ($filtered['folderCounts'][$folder]??-1)===0,'search with no matches clears folder counts');
$filtered=$docs->listing($u,['scope'=>'all','query'=>'D'.$id,'folderCounts'=>'1']);
check($filtered['total']===0 && !array_key_exists($folder,$filtered['folderCounts']),'search counts respect owner and folder visibility');
check(($docs->folderCounts($a)[$folder]??-1)===0 && ($docs->folderCounts($a)[$child]??0)===1,'folder display counts exclude descendants');
check(($docs->folderCounts($u)[$folder]??null)===null,'folder display counts keep owner boundaries');
$docs->folderWrite($a,'create',0,'Target'); $targetFolder=(int)array_values(array_filter($docs->folders($a),fn($row)=>(string)$row['name']==='Target'))[0]['id'];
$docs->folderWrite($a,'move',$child,'Child A',$targetFolder); $moved=(array_values(array_filter($docs->folders($a),fn($row)=>(int)$row['id']===$child)))[0];
check((int)$moved['parent_id']===$targetFolder && $docs->listing($a,['scope'=>(string)$targetFolder])['total']===0 && $docs->listing($a,['scope'=>(string)$child])['total']===1,'folder move keeps links in child only');
$docs->folderWrite($a,'move',$child,'Child A',null); $moved=(array_values(array_filter($docs->folders($a),fn($row)=>(int)$row['id']===$child)))[0];
check($moved['parent_id']===null,'folder moves back to top level');
$docs->folderWrite($a,'move',$child,'Child A',$folder);
rejects(fn()=>$docs->folderWrite($a,'move',$folder,'Folder A',$child),'moving folder into its own descendant rejected');
$docs->folderWrite($a,'create',0,'Child A');
rejects(fn()=>$docs->folderWrite($a,'move',$child,'Child A',null),'name conflict on target level rejected');
$docs->folderWrite($a,'rename',(int)array_values(array_filter($docs->folders($a),fn($row)=>(string)$row['name']==='Child A' && (int)$row['id']!==$child))[0]['id'],'Child A root conflict');
$doc=$docs->get($a,$id);
$docs->folderWrite($b,'create',0,'Folder B'); $foreignFolder=(int)$docs->folders($b)[0]['id'];
rejects(fn()=>$docs->link($a,$id,2,$foreignFolder,false),'foreign folder linking denied');
rejects(fn()=>$docs->link($u,$own,1,$folder,false),'user cannot link into another owners folder');
$docs->link($a,$id,(int)$doc['revision'],$folder,false);
check($docs->listing($a,['scope'=>(string)$folder])['total']===1,'multiple nested links do not duplicate document');
$display=$docs->listing($a,['scope'=>(string)$folder])['rows'][0];
check((int)$display['folder_count']===2 && $display['tag_names']===['Invoice'] && ($docs->folderCounts($a)[$folder]??0)===1,'list badges count direct links and all tags while parent count stays distinct');
check($evaluation->bookingSummary($a,['folder'=>(string)$folder])['selectedTotal']===1 && abs($evaluation->bookingSummary($a,['folder'=>(string)$folder])['currencies']['EUR']['gross']-119)<0.001,'evaluation folder counts a directly linked booking once despite multiple folder links');
check($evaluation->bookingSummary($a,['folder'=>(string)$child])['selectedTotal']===1 && abs($evaluation->bookingSummary($a,['folder'=>(string)$child])['currencies']['EUR']['gross']-119)<0.001,'evaluation includes direct child links');
check($evaluation->bookingSummary($a,['folders'=>[(string)$folder,(string)$child]])['selectedTotal']===1 && abs($evaluation->bookingSummary($a,['folders'=>[(string)$folder,(string)$child]])['currencies']['EUR']['gross']-119)<0.001,'evaluation accepts multiple folders and counts a document linked to both only once');
check(abs($evaluation->bookingSummary($a,['folder'=>(string)$child,'query'=>'D'.$id,'tag'=>(string)$tag,'amountFrom'=>'119','resultView'=>'latest','latestCount'=>'1'])['currencies']['EUR']['gross']-119)<0.001,'evaluation intersects folder, search, tag, amount and latest-N filters');
rejects(fn()=>$evaluation->bookingSummary($u,['folder'=>(string)$folder]),'user cannot select another owners folder in evaluation');
rejects(fn()=>$evaluation->bookingSummary($b,['folder'=>(string)$folder]),'foreign tenant folder is rejected in evaluation');
rejects(fn()=>$evaluation->bookingSummary($a,['folders'=>[(string)$folder,(string)$foreignFolder]]),'multiple evaluation folders retain tenant boundaries');
rejects(fn()=>$evaluation->bookingSummary($a,['folder'=>'99999999']),'unknown evaluation folder is rejected');
check(count($display['folder_ids'])===2 && in_array($folder,$display['folder_ids'],true) && in_array($child,$display['folder_ids'],true),'folder tooltip receives the directly linked visible folder IDs');
$docs->createTag($a,'Bulk tag'); $bulkTag=(int)array_values(array_filter($docs->tags($a),fn($row)=>(string)$row['name']==='Bulk tag'))[0]['id'];
$unlinkDoc=$docs->get($a,$id);
$unlinkPlan=['documents'=>[['id'=>$id,'revision'=>(int)$unlinkDoc['revision']]],'folderAction'=>'remove','folderId'=>$folder,'tagAction'=>'keep','tags'=>[],'ownerId'=>'','status'=>'keep'];
check($docs->bulk($a,$unlinkPlan)===1,'bulk unlink reports the removed direct link');
$unlinked=$docs->get($a,$id);
check(array_map('intval',$unlinked['folders'])===[$child] && $unlinked['tags']===$unlinkDoc['tags'],'bulk unlink preserves child links and tags');
check($docs->listing($a,['scope'=>(string)$folder,'query'=>'D'.$id])['total']===0,'unlinked document is no longer visible in parent');
$unlinkPlan['documents'][0]['revision']=(int)$unlinked['revision'];
rejects(fn()=>$docs->bulk($a,$unlinkPlan),'unlink without a direct link reports an error instead of false success');
check($docs->get($a,$id)===$unlinked,'no-op unlink leaves document and revision unchanged');
$docs->link($a,$id,(int)$unlinked['revision'],$folder,false);
$older=$docs->get($a,$olderNeedle); $newer=$docs->get($a,$newerNeedle);
$changed=$docs->bulk($a,['documents'=>[['id'=>$olderNeedle,'revision'=>(int)$older['revision']],['id'=>$newerNeedle,'revision'=>(int)$newer['revision']]],'folderAction'=>'add','folderId'=>$folder,'tagAction'=>'add','tags'=>[$bulkTag],'ownerId'=>'','status'=>'keep']);
check($changed===2 && $docs->listing($a,['scope'=>(string)$folder,'query'=>'Needle'])['total']===2 && (int)sql('SELECT COUNT(*) FROM document_tags WHERE tenant_id=? AND tag_id=? AND document_id IN (?,?)',[$a->tenantId(),$bulkTag,$olderNeedle,$newerNeedle])->fetchColumn()===2,'bulk add links folders and tags without duplicate associations');
$docs->folderWrite($a,'create',0,'Move target'); $moveTarget=(int)array_values(array_filter($docs->folders($a),fn($row)=>(string)$row['name']==='Move target'))[0]['id'];
$newer=$docs->get($a,$newerNeedle); $docs->link($a,$newerNeedle,(int)$newer['revision'],$child,false);
$newer=$docs->get($a,$newerNeedle);
$docs->bulk($a,['documents'=>[['id'=>$newerNeedle,'revision'=>(int)$newer['revision']]],'folderAction'=>'move','folderId'=>$moveTarget,'sourceFolderId'=>$folder,'tagAction'=>'keep','tags'=>[],'ownerId'=>'','status'=>'keep']);
$links=array_map('intval',sql('SELECT folder_id FROM folder_documents WHERE tenant_id=? AND document_id=? ORDER BY folder_id',[$a->tenantId(),$newerNeedle])->fetchAll(PDO::FETCH_COLUMN));
check(in_array($child,$links,true) && in_array($moveTarget,$links,true) && !in_array($folder,$links,true),'bulk move replaces only the selected source folder link and keeps other folder links');
$newer=$docs->get($a,$newerNeedle);
$docs->bulk($a,['documents'=>[['id'=>$newerNeedle,'revision'=>(int)$newer['revision']]],'folderAction'=>'move','folderId'=>$folder,'sourceFolderId'=>$moveTarget,'tagAction'=>'keep','tags'=>[],'ownerId'=>'','status'=>'keep']);
$older=$docs->get($a,$olderNeedle); $newer=$docs->get($a,$newerNeedle);
$ownRow=$docs->get($u,$own);
rejects(fn()=>$docs->bulk($u,['documents'=>[['id'=>$own,'revision'=>(int)$ownRow['revision']],['id'=>$newerNeedle,'revision'=>(int)$newer['revision']]],'folderAction'=>'keep','tagAction'=>'add','tags'=>[$bulkTag],'ownerId'=>'','status'=>'keep']),'mixed owner selection is rejected before any bulk change');
check((int)sql('SELECT COUNT(*) FROM document_tags WHERE tenant_id=? AND document_id=? AND tag_id=?',[$a->tenantId(),$own,$bulkTag])->fetchColumn()===0,'rejected mixed owner selection leaves permitted document unchanged');
rejects(fn()=>$docs->bulk($a,['documents'=>[['id'=>$olderNeedle,'revision'=>(int)$older['revision']-1],['id'=>$newerNeedle,'revision'=>(int)$newer['revision']]],'folderAction'=>'remove-all','tagAction'=>'keep','tags'=>[],'ownerId'=>'','status'=>'keep']),'stale bulk revision rejects the complete selection');
check($docs->listing($a,['scope'=>(string)$folder,'query'=>'Needle'])['total']===2,'stale bulk revision leaves all folder links unchanged');
rejects(fn()=>$docs->bulk($a,['documents'=>[['id'=>$olderNeedle,'revision'=>(int)$older['revision']],['id'=>$newerNeedle,'revision'=>(int)$newer['revision']]],'folderAction'=>'keep','tagAction'=>'set','tags'=>[$foreignTag],'ownerId'=>'','status'=>'keep']),'foreign bulk tag rejects the complete selection');
check((int)sql('SELECT COUNT(*) FROM document_tags WHERE tenant_id=? AND tag_id=? AND document_id IN (?,?)',[$a->tenantId(),$bulkTag,$olderNeedle,$newerNeedle])->fetchColumn()===2,'invalid bulk tag leaves all existing tags unchanged');
$older=$docs->get($a,$olderNeedle); $newer=$docs->get($a,$newerNeedle);
$docs->bulk($a,['documents'=>[['id'=>$olderNeedle,'revision'=>(int)$older['revision']],['id'=>$newerNeedle,'revision'=>(int)$newer['revision']]],'folderAction'=>'keep','tagAction'=>'keep','tags'=>[],'ownerId'=>'','status'=>'trash']);
check($docs->listing($a,['scope'=>'trash','query'=>'Needle','includeExpired'=>'1','includeNotSearchable'=>'1'])['total']===2,'bulk status action moves all selected documents to trash');
$trashSearch=$docs->listing($a,['scope'=>'all','query'=>'Needle','folderCounts'=>'1']);
check($trashSearch['total']===2 && $trashSearch['trashCount']===2,'global search includes matching trash documents and its count');
$older=$docs->get($a,$olderNeedle); $newer=$docs->get($a,$newerNeedle);
$docs->bulk($a,['documents'=>[['id'=>$olderNeedle,'revision'=>(int)$older['revision']],['id'=>$newerNeedle,'revision'=>(int)$newer['revision']]],'folderAction'=>'keep','tagAction'=>'keep','tags'=>[],'ownerId'=>'','status'=>'restore']);
check($docs->listing($a,['scope'=>(string)$folder,'query'=>'Needle'])['total']===2 && (int)sql('SELECT COUNT(*) FROM document_tags WHERE tenant_id=? AND tag_id=? AND document_id IN (?,?)',[$a->tenantId(),$bulkTag,$olderNeedle,$newerNeedle])->fetchColumn()===2,'bulk restore preserves links and tags');
$older=$docs->get($a,$olderNeedle);
$docs->bulk($a,['documents'=>[['id'=>$olderNeedle,'revision'=>(int)$older['revision']]],'folderAction'=>'keep','tagAction'=>'keep','tags'=>[],'ownerId'=>(string)$u->id(),'status'=>'keep']);
check((int)$docs->get($u,$olderNeedle)['id']===$olderNeedle,'admin bulk owner change transfers a document to the selected active tenant user');
$older=$docs->get($a,$olderNeedle); $newer=$docs->get($a,$newerNeedle);
$docs->bulk($a,['documents'=>[['id'=>$olderNeedle,'revision'=>(int)$older['revision']],['id'=>$newerNeedle,'revision'=>(int)$newer['revision']]],'folderAction'=>'remove-all','tagAction'=>'keep','tags'=>[],'ownerId'=>'','status'=>'keep']);
check($docs->listing($a,['scope'=>(string)$folder,'query'=>'Needle'])['total']===0,'bulk remove-all removes only selected document links');
$folderPreview=$docs->folderDeletePreview($a,$folder);
check($folderPreview['folders']>=1 && $folderPreview['documents']>=1,'folder deletion preview counts descendants and linked documents');
$doc=$docs->get($a,$id); $docs->save($a,$id,(int)$doc['revision'],['title'=>'Hidden','expired'=>'1','notSearchable'=>'1','tags'=>[$tag]]);
check($docs->listing($a,['scope'=>'all','query'=>'D'.$id])['total']===0,'ID search does not bypass hidden flags');
check($evaluation->bookingSummary($a,['query'=>'D'.$id])['selectedTotal']===0 && abs($evaluation->bookingSummary($a,['query'=>'D'.$id,'includeExpired'=>'1','includeNotSearchable'=>'1'])['currencies']['EUR']['gross']-119)<0.001,'evaluation status filters match detailed document search');
check($docs->listing($a,['scope'=>'all','query'=>'D'.$id,'includeExpired'=>'1','includeNotSearchable'=>'1'])['total']===1,'both explicit detail flags restore search result');
$doc=$docs->get($a,$id); $docs->status($a,$id,(int)$doc['revision'],'trash');
check(($docs->folderCounts($a)[$folder]??0)===0 && $docs->trashCount($a)>=1 && $docs->trashCount($u)===0,'trash excludes documents from folder counts and counts only visible owners');
$folderPreview=$docs->folderDeletePreview($a,$folder);
$beforeFolderRevision=(int)$docs->get($a,$id)['revision'];
$docs->folderWrite($a,'delete',$folder,'',null,$folderPreview['fingerprint']);
check($docs->get($a,$id)['folders']===[] && (int)$docs->get($a,$id)['revision']===$beforeFolderRevision+1 && !in_array($folder,array_column($docs->folders($a),'id')) && !in_array($child,array_column($docs->folders($a),'id')),'deleting populated folder removes its subtree and links, not trash documents');
$docs->folderWrite($a,'create',0,'Delete tree root'); $deleteRoot=(int)array_values(array_filter($docs->folders($a),fn($row)=>$row['name']==='Delete tree root'))[0]['id'];
$docs->folderWrite($a,'create',0,'Delete tree child',$deleteRoot); $deleteChild=(int)array_values(array_filter($docs->folders($a),fn($row)=>$row['name']==='Delete tree child'))[0]['id'];
$docs->folderWrite($a,'create',0,'Outside tree'); $outside=(int)array_values(array_filter($docs->folders($a),fn($row)=>$row['name']==='Outside tree'))[0]['id'];
$linkedDoc=$docs->ingest($a,$tmp.'/sample.pdf','Linked in three folders.pdf');
foreach ([$deleteRoot,$deleteChild,$outside] as $folderId) { $row=$docs->get($a,$linkedDoc); $docs->link($a,$linkedDoc,(int)$row['revision'],$folderId,false); }
$trashLinked=$docs->ingest($a,$tmp.'/sample.pdf','Trash in child.pdf'); $row=$docs->get($a,$trashLinked); $docs->link($a,$trashLinked,(int)$row['revision'],$deleteChild,false);
$row=$docs->get($a,$trashLinked); $docs->status($a,$trashLinked,(int)$row['revision'],'trash');
$preview=$docs->folderDeletePreview($a,$deleteRoot);
check($preview['folders']===1 && $preview['documents']===2,'folder deletion counts each affected document once including trash links');
$laterLink=$docs->ingest($a,$tmp.'/sample.pdf','Later folder link.pdf'); $row=$docs->get($a,$laterLink); $docs->link($a,$laterLink,(int)$row['revision'],$deleteRoot,false);
rejects(fn()=>$docs->folderWrite($a,'delete',$deleteRoot,'',null,$preview['fingerprint']),'changed folder contents require a new deletion confirmation');
check(count($docs->get($a,$linkedDoc)['folders'])===3,'stale deletion confirmation changes no links');
$preview=$docs->folderDeletePreview($a,$deleteRoot); $docs->folderWrite($a,'delete',$deleteRoot,'',null,$preview['fingerprint']);
check($preview['documents']===3 && $docs->get($a,$linkedDoc)['folders']===[$outside] && $docs->get($a,$trashLinked)['deleted_at']!==null && $docs->get($a,$laterLink)['folders']===[],'recursive folder deletion preserves documents and unrelated links');
rejects(fn()=>$docs->folderDeletePreview($b,$outside),'foreign tenant cannot preview folder deletion');
$docs->folderWrite($u,'create',0,'User parent with admin child'); $mixedParent=(int)array_values(array_filter($docs->folders($u),fn($row)=>$row['name']==='User parent with admin child'))[0]['id'];
$docs->folderWrite($a,'create',0,'Admin owned child',$mixedParent);
rejects(fn()=>$docs->folderDeletePreview($u,$mixedParent),'normal user cannot delete a foreign-owned descendant');
$preview=$docs->folderDeletePreview($a,$mixedParent); $docs->folderWrite($a,'delete',$mixedParent,'',null,$preview['fingerprint']);
$docs->folderWrite($u,'create',0,'User folder with foreign document'); $mixedDocuments=(int)array_values(array_filter($docs->folders($u),fn($row)=>$row['name']==='User folder with foreign document'))[0]['id'];
$row=$docs->get($a,$linkedDoc); $docs->link($a,$linkedDoc,(int)$row['revision'],$mixedDocuments,false);
rejects(fn()=>$docs->folderDeletePreview($u,$mixedDocuments),'normal user cannot delete a folder linked to a foreign document');
$preview=$docs->folderDeletePreview($a,$mixedDocuments); $docs->folderWrite($a,'delete',$mixedDocuments,'',null,$preview['fingerprint']);
check($docs->get($a,$linkedDoc)['folders']===[$outside],'admin folder deletion preserves the documents other folder links');
$doc=$docs->get($a,$id); $docs->status($a,$id,(int)$doc['revision'],'restore');
check($docs->get($a,$id)['deleted_at']===null,'trash restore keeps original');
$opened=$docs->open($a,$id); check(stream_get_contents($opened['handle'])===file_get_contents($tmp.'/sample.pdf'),'authorized stream returns exact original'); fclose($opened['handle']);
$original=file_get_contents($target.'/'.$file['relative_path']); file_put_contents($target.'/'.$file['relative_path'],str_replace('Catalog','Changed',$original));
rejects(fn()=>$docs->open($a,$id),'same-size content tampering rejected by checksum'); file_put_contents($target.'/'.$file['relative_path'],$original);
$path=$target.'/'.$file['relative_path']; rename($path,$path.'.held'); symlink($path.'.held',$path);
rejects(fn()=>$docs->open($a,$id),'file symlink rejected'); unlink($path); rename($path.'.held',$path);
$theme=['mode'=>'dark','density'=>'compact','fontFamily'=>'serif','fontSize'=>150,'light'=>['accent'=>'#123456','background'=>'#f3f4f0','surface'=>'#ffffff'],'dark'=>['accent'=>'#abcdef','background'=>'#141b1a','surface'=>'#1d2725']];
$docs->preferences($a,['widths'=>[20,25,30,25],'mode'=>'dark','theme'=>$theme]);
$savedPreferences=$docs->preferences($a);
check($savedPreferences['mode']==='dark' && $savedPreferences['theme']['fontFamily']==='serif' && $docs->preferences($u)['mode']==='system','appearance, colors and widths are user scoped');
rejects(fn()=>$docs->preferences($a,['widths'=>[1,1,1,1],'mode'=>'dark']),'invalid layout rejected');
$ownRow=$docs->get($u,$own);
$ownInput=['title'=>'Own tagged document','tags'=>[$tag],'newTags'=>['Neue Kategorie']];
$docs->save($u,$own,(int)$ownRow['revision'],$ownInput);
$createdTag=(int)sql('SELECT id FROM tags WHERE tenant_id=? AND normalized_name=?',[$a->tenantId(),'neue kategorie'])->fetchColumn();
check($createdTag>0 && in_array($createdTag,$docs->get($u,$own)['tags'],true),'user may create and attach a confirmed new tag while saving own document');
$ownRow=$docs->get($u,$own);
$docs->save($u,$own,(int)$ownRow['revision'],['title'=>'Own tagged document','tags'=>[$tag],'newTags'=>['nEuE kAtEgOrIe']]);
check((int)sql('SELECT COUNT(*) FROM tags WHERE tenant_id=? AND normalized_name=?',[$a->tenantId(),'neue kategorie'])->fetchColumn()===1 && count($docs->get($u,$own)['tags'])===2,'case-insensitive tag reuse creates no duplicate');
$ownRow=$docs->get($u,$own); $tagCount=(int)sql('SELECT COUNT(*) FROM tags WHERE tenant_id=?',[$a->tenantId()])->fetchColumn();
rejects(fn()=>$docs->save($u,$own,(int)$ownRow['revision']-1,['title'=>'Stale','tags'=>[],'newTags'=>['Stale category']]),'stale revision cannot create a tag');
rejects(fn()=>$docs->save($u,$id,(int)$docs->get($a,$id)['revision'],['title'=>'Foreign owner','tags'=>[],'newTags'=>['Forbidden category']]),'new tag cannot bypass document ownership');
rejects(fn()=>$docs->save($b,$own,(int)$ownRow['revision'],['title'=>'Foreign tenant','tags'=>[],'newTags'=>['Foreign category']]),'new tag cannot bypass tenant isolation');
rejects(fn()=>$docs->save($u,$own,(int)$ownRow['revision'],['title'=>'Invalid tag','tags'=>[],'newTags'=>['   ']]),'empty new tag rejected');
check((int)sql('SELECT COUNT(*) FROM tags WHERE tenant_id=?',[$a->tenantId()])->fetchColumn()===$tagCount && $docs->get($u,$own)['title']==='Own tagged document','failed tag saves leave catalogue and document unchanged');
$db->prepare('UPDATE tags SET active=0 WHERE tenant_id=? AND id=?')->execute([$a->tenantId(),$createdTag]);
rejects(fn()=>$docs->save($u,$own,(int)$ownRow['revision'],['title'=>'Inactive tag','tags'=>[],'newTags'=>['NEUE KATEGORIE']]),'inactive catalogue tag is not silently recreated');
check((int)sql('SELECT COUNT(*) FROM tags WHERE tenant_id=?',[$a->tenantId()])->fetchColumn()===$tagCount && $docs->get($u,$own)['title']==='Own tagged document','inactive tag rejection is atomic');
$docs->createTag($a,'Cleanup tag'); $cleanupTag=(int)sql('SELECT id FROM tags WHERE tenant_id=? AND normalized_name=?',[$a->tenantId(),'cleanup tag'])->fetchColumn();
$taggedOne=$docs->ingest($u,$tmp.'/sample.pdf','Tag one.pdf'); $taggedTwo=$docs->ingest($a,$tmp.'/sample.pdf','Tag two.pdf');
foreach ([[$u,$taggedOne],[$a,$taggedTwo]] as [$person,$documentId]) { $row=$docs->get($person,$documentId); $docs->save($person,$documentId,(int)$row['revision'],['title'=>'Tagged','tags'=>[$cleanupTag]]); }
$row=$docs->get($a,$taggedTwo); $docs->status($a,$taggedTwo,(int)$row['revision'],'trash');
$catalogue=array_values(array_filter($docs->tagCatalogue($a,'cleanup'),static fn($row)=>(int)$row['id']===$cleanupTag));
check(count($catalogue)===1 && (int)$catalogue[0]['document_count']===2,'tag administration counts active and trash documents');
$userTagCatalogue=array_values(array_filter($docs->tagCatalogue($u,'cleanup'),static fn($row)=>(int)$row['id']===$cleanupTag));
check(count($userTagCatalogue)===1 && (int)$userTagCatalogue[0]['document_count']===1 && !$userTagCatalogue[0]['manageable'],'normal user sees only own tag usage and cannot manage shared tag');
rejects(fn()=>$docs->renameTag($u,$cleanupTag,'Forbidden'),'normal user cannot rename tag used on foreign documents');
rejects(fn()=>$docs->renameTag($a,$cleanupTag,'Invoice'),'tag rename rejects existing normalized name');
$docs->renameTag($a,$cleanupTag,'Renamed cleanup');
check(in_array($cleanupTag,$docs->get($u,$taggedOne)['tags'],true) && (int)sql('SELECT COUNT(*) FROM tags WHERE tenant_id=? AND id=? AND name=?',[$a->tenantId(),$cleanupTag,'Renamed cleanup'])->fetchColumn()===1,'renaming a tag preserves stable document links');
sql("INSERT INTO import_sources (tenant_id,owner_id,kind,name,enabled,config_json) VALUES (?,?,'inbound','Tag cleanup source',1,?)",[$a->tenantId(),$a->id(),json_encode(['acceptance'=>['tags'=>[$cleanupTag]]])]); $sourceId=(int)$db->lastInsertId();
rejects(fn()=>$docs->deleteTag($a,$cleanupTag,1),'tag deletion refuses a stale affected-document count');
rejects(fn()=>$docs->deleteTag($u,$cleanupTag,1),'normal user cannot delete tag used on foreign documents');
rejects(fn()=>$docs->deleteTag($b,$cleanupTag,2),'foreign tenant cannot delete catalogue tags');
$taggedRevision=(int)$docs->get($u,$taggedOne)['revision']; $trashTaggedRevision=(int)$docs->get($a,$taggedTwo)['revision'];
check($docs->deleteTag($a,$cleanupTag,2)===2 && !in_array($cleanupTag,$docs->get($u,$taggedOne)['tags'],true) && !in_array($cleanupTag,$docs->get($a,$taggedTwo)['tags'],true),'confirmed deletion removes a tag from active and trash documents');
check((int)$docs->get($u,$taggedOne)['revision']===$taggedRevision+1 && (int)$docs->get($a,$taggedTwo)['revision']===$trashTaggedRevision+1,'tag deletion advances affected document revisions');
$sourceConfig=json_decode((string)sql('SELECT config_json FROM import_sources WHERE id=?',[$sourceId])->fetchColumn(),true);
check($sourceConfig['acceptance']['tags']===[] && (int)sql('SELECT COUNT(*) FROM tags WHERE tenant_id=? AND id=?',[$a->tenantId(),$cleanupTag])->fetchColumn()===0,'deleted tag is also removed from configured source acceptance');
$ownUserTag=(int)sql('SELECT id FROM tags WHERE tenant_id=? AND normalized_name=?',[$a->tenantId(),'user category'])->fetchColumn();
$docs->renameTag($u,$ownUserTag,'Own renamed category');
check($docs->deleteTag($u,$ownUserTag,0)===0 && (int)sql('SELECT COUNT(*) FROM tags WHERE tenant_id=? AND id=?',[$a->tenantId(),$ownUserTag])->fetchColumn()===0,'normal user can rename and delete a tag not used by others');
$docs->createTag($u,'Source shared category'); $sourceOnlyTag=(int)sql('SELECT id FROM tags WHERE tenant_id=? AND normalized_name=?',[$a->tenantId(),'source shared category'])->fetchColumn();
sql('UPDATE import_sources SET config_json=? WHERE id=?',[json_encode(['acceptance'=>['tags'=>[$sourceOnlyTag]]]),$sourceId]);
rejects(fn()=>$docs->deleteTag($u,$sourceOnlyTag,0),'normal user cannot delete a tag configured in another owners source');
$retention=new TrashRetention($db,$root);
check($retention->days($u)===0,'missing personal trash retention defaults to unlimited');
rejects(fn()=>$retention->saveDays($u,1,false),'activating trash retention requires explicit acknowledgement');
$retention->saveDays($u,1,true); check($retention->days($u)===1 && $retention->days($a)===0,'trash retention is personal to owner and tenant');
$purgeDoc=$docs->ingest($u,$tmp.'/sample.pdf','Purge me.pdf'); $purgeFile=(string)sql('SELECT relative_path FROM document_files WHERE document_id=?',[$purgeDoc])->fetchColumn();
$row=$docs->get($u,$purgeDoc); $docs->status($u,$purgeDoc,(int)$row['revision'],'trash');
sql('UPDATE documents SET deleted_at=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 2 DAY) WHERE tenant_id=? AND id=?',[$a->tenantId(),$purgeDoc]);
check($retention->run(1)===1 && $retention->workerActive() && !is_file($target.'/'.$purgeFile),'expired trash file is permanently removed by the bounded server job');
check((int)sql('SELECT COUNT(*) FROM documents WHERE tenant_id=? AND id=?',[$a->tenantId(),$purgeDoc])->fetchColumn()===0 && (int)sql("SELECT COUNT(*) FROM audit_events WHERE tenant_id=? AND action='document.purged' AND entity_id=?",[$a->tenantId(),(string)$purgeDoc])->fetchColumn()===1,'expired document and associations are deleted with an audit trail');
$retention->saveDays($u,0,false);
$unlimitedDoc=$docs->ingest($u,$tmp.'/sample.pdf','Keep indefinitely.pdf'); $row=$docs->get($u,$unlimitedDoc); $docs->status($u,$unlimitedDoc,(int)$row['revision'],'trash');
sql('UPDATE documents SET deleted_at=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 20 DAY) WHERE tenant_id=? AND id=?',[$a->tenantId(),$unlimitedDoc]);
check($retention->days($u)===0 && $retention->run(1)===0 && $docs->get($u,$unlimitedDoc)!==[], 'zero days keeps even old trash indefinitely while worker runs');
$recoverDoc=$docs->ingest($u,$tmp.'/sample.pdf','Recover stage.pdf'); $recoverFile=(string)sql('SELECT relative_path FROM document_files WHERE document_id=?',[$recoverDoc])->fetchColumn();
$row=$docs->get($u,$recoverDoc); $docs->status($u,$recoverDoc,(int)$row['revision'],'trash');
rename($target.'/'.$recoverFile,$target.'/'.$recoverFile.'.o8-purge-'.$recoverDoc);
sql('INSERT INTO platform_settings (setting_key,value_json) VALUES (?,?)',['trash.retention.pending',json_encode(['tenant'=>$a->tenantId(),'document'=>$recoverDoc,'files'=>[$recoverFile]])]);
check($retention->run(1)===0 && is_file($target.'/'.$recoverFile) && !is_file($target.'/'.$recoverFile.'.o8-purge-'.$recoverDoc),'interrupted purge restores staged files when document still exists');
$manualSnapshot=$retention->manualInfo($u); $manualIds=array_column($manualSnapshot['items'],'id');
check($manualSnapshot['count']>=2 && in_array($unlimitedDoc,$manualIds,true) && in_array($recoverDoc,$manualIds,true) && !in_array($taggedTwo,$manualIds,true),'manual trash snapshot contains only the users own deleted documents');
check($retention->manualInfo($a)['count']>$manualSnapshot['count'] && $retention->manualInfo($b)['count']===0,'admin sees tenant trash while another tenant sees none');
$laterDoc=$docs->ingest($u,$tmp.'/sample.pdf','Trashed after confirmation.pdf'); $row=$docs->get($u,$laterDoc); $docs->status($u,$laterDoc,(int)$row['revision'],'trash');
check(!in_array($laterDoc,$manualIds,true),'documents trashed after confirmation are excluded from its snapshot');
check($retention->manualPurge($u,$taggedTwo,(int)$docs->get($a,$taggedTwo)['revision'])===false && $retention->manualPurge($b,$recoverDoc,(int)$docs->get($u,$recoverDoc)['revision'])===false,'manual purge cannot affect foreign owner or tenant trash');
rejects(fn()=>$retention->manualPurge($u,$unlimitedDoc,(int)$docs->get($u,$unlimitedDoc)['revision']-1),'manual purge rejects stale document revision');
$manualRemoved=0; foreach ($manualSnapshot['items'] as $item) $manualRemoved+=(int)$retention->manualPurge($u,$item['id'],$item['revision']);
check($manualRemoved===$manualSnapshot['count'] && $docs->trashCount($u)===1 && !is_file($target.'/'.$recoverFile),'manual purge permanently deletes snapshot files even when retention is unlimited');
$adminSnapshot=$retention->manualInfo($a); foreach ($adminSnapshot['items'] as $item) $retention->manualPurge($a,$item['id'],$item['revision']);
check($docs->trashCount($a)===0 && $docs->trashCount($u)===0,'admin can empty all remaining tenant trash');
$admin->updateUser($a,$u->id(),(int)$u->row['auth_version'],'Blocked','user',false);
rejects(fn()=>$docs->get($u,$own),'revoked actor cannot read');
rejects(fn()=>$docs->ingest($u,$tmp.'/sample.pdf','stale.pdf'),'revoked actor cannot ingest');
$txtId=$docs->ingest($a,$tmp.'/note.txt','note.txt'); $txtFile=sql("SELECT relative_path,mime_type FROM document_files WHERE document_id=? AND role='original'",[$txtId])->fetch();
$odtId=$docs->ingest($a,$tmp.'/note.odt','note.odt'); $odtFile=sql("SELECT relative_path,mime_type FROM document_files WHERE document_id=? AND role='original'",[$odtId])->fetch();
check($txtFile['mime_type']==='text/plain' && str_ends_with((string)$txtFile['relative_path'],'.txt') && $odtFile['mime_type']==='application/vnd.oasis.opendocument.text' && str_ends_with((string)$odtFile['relative_path'],'.odt'),'TXT and ODT originals use regular safe ingestion');
$deletion=new TenantDeletion($db,$root);
sql('INSERT INTO platform_settings (setting_key,value_json) VALUES (?,?)',['trash.retention.pending',json_encode(['tenant'=>$a->tenantId(),'document'=>$recoverDoc,'files'=>[]])]);
rejects(fn()=>$deletion->start($op,$a->tenantId(),$uuid,'Alpha'),'tenant deletion waits for pending trash purge recovery');
$retention->run(1);
$job=$deletion->start($op,$a->tenantId(),$uuid,'Alpha');
rejects(fn()=>$docs->open($a,$id),'deleting tenant cannot stream');
$steps=0; while ($job['phase']!=='done' && ++$steps<100) $job=$deletion->step($op,$a->tenantId());
check($job['phase']==='done' && !is_dir($target),'tenant deletion handles real originals and storage marker');
check(is_dir($base.'/'.$second),'other tenant storage preserved');
echo "$checks storage/document backend checks passed.\n";
