<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
use O8\Core\Runtime;
use O8\Install\Migrator;
use O8\Auth\{AuthService,InvitationService};
use O8\Admin\Administration;
if (PHP_SAPI!=='cli' || !preg_match('#^/tmp/o8-m2-test\.[A-Za-z0-9]+/db\.sock$#D',$argv[1]??'')) exit("Isolated test socket required.\n");
$db=new PDO('mysql:unix_socket='.$argv[1].';charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$test='shared_test_'.bin2hex(random_bytes(4)); $db->exec('CREATE DATABASE '.$test); $db->exec('USE '.$test);
$tmp=dirname($argv[1]).'/'.$test; mkdir($tmp); mkdir($tmp.'/legacy');
foreach (['001_core.sql','002_tenant_name_unique.sql'] as $file) copy(dirname(__DIR__).'/database/migrations/'.$file,$tmp.'/legacy/'.$file);
$runtime=new Runtime($tmp.'/runtime'); $identity=$runtime->identity(); (new Migrator($db,$tmp.'/legacy'))->install($identity);
$checks=0;
function check(bool $ok,string $label): void { global $checks; if (!$ok) throw new RuntimeException('FAIL '.$label); ++$checks; echo "PASS $label\n"; }
function rejects(callable $call,string $label): void { try { $call(); } catch (RuntimeException|InvalidArgumentException $e) { check(true,$label); return; } check(false,$label); }
function sql(string $query,array $params=[]): PDOStatement { global $db; $s=$db->prepare($query); $s->execute($params); return $s; }
$hash=password_hash('shared-secret',PASSWORD_DEFAULT);
sql("UPDATE platform_operators SET password_hash=?,must_change_password=0,bootstrap_pending=0 WHERE id=1",[$hash]);
foreach (['Alpha','Beta'] as $name) {
    sql('INSERT INTO tenants (public_id,name) VALUES (?,?)',[Runtime::uuid(),$name]); $tid=(int)$db->lastInsertId();
    sql("INSERT INTO roles VALUES (?,'admin','Admin',1),(?,'user','User',1)",[$tid,$tid]);
    sql("INSERT INTO users (tenant_id,login,display_name,email,email_normalized,password_hash,must_change_password,role,last_login_at) VALUES (?,'legacy','Legacy','same@example.test','same@example.test',?,0,'admin','2026-09-01 12:00:00')",[$tid,$hash]);
}
sql("INSERT INTO documents (tenant_id,owner_id,title,source_type) VALUES (1,1,'Preserved','test')");
$m=new Migrator($db,dirname(__DIR__).'/database/migrations');
rejects(fn()=>$m->upgrade($identity),'duplicate legacy identities stop upgrade without merging');
check((int)sql("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='accounts'")->fetchColumn()===0,'conflict is detected before schema changes');
sql("UPDATE users SET login='beta' WHERE id=2");
rejects(fn()=>$m->upgrade($identity),'matching legacy email alone never merges accounts');
sql("UPDATE users SET login='same@example.test',email='beta@example.test',email_normalized='beta@example.test' WHERE id=2");
rejects(fn()=>$m->upgrade($identity),'legacy username versus email ambiguity rejected');
sql("UPDATE users SET login='beta' WHERE id=2");
sql("INSERT INTO platform_settings (setting_key,value_json) VALUES ('tenant.delete.1','{}')");
rejects(fn()=>$m->upgrade($identity),'pending deletion prevents incompatible upgrade');
sql("DELETE FROM platform_settings WHERE setting_key='tenant.delete.1'");
$m->upgrade($identity); $m->upgrade($identity);
check($m->current(),'migration repeatable and complete');
check(sql('SELECT password_hash FROM accounts WHERE id=1')->fetchColumn()===$hash,'legacy password hash unchanged');
check(sql('SELECT last_login_at FROM accounts WHERE id=1')->fetchColumn()==='2026-09-01 12:00:00','login history retained');
check((int)sql('SELECT owner_id FROM documents WHERE id=1')->fetchColumn()===1,'document ownership unchanged');
check((int)sql('SELECT account_id FROM users WHERE id=1')->fetchColumn()===1,'membership identifier retained');
check((int)sql('SELECT COUNT(*) FROM accounts')->fetchColumn()===2,'independent legacy accounts remain independent');
$auth=new AuthService($db,$runtime,$identity['key']); $admin=new Administration($db); $invites=new InvitationService($db);
$opSession=$auth->login('operator','admin','shared-secret','test'); $operator=$auth->actor($opSession);
$aSession=$auth->login('account',' LEGACY ','shared-secret','test'); $a=$auth->actor($aSession);
$bSession=$auth->login('account','beta@example.test','shared-secret','test'); $b=$auth->actor($bSession);
check($a->kind==='tenant' && $a->tenantId()===1,'one membership auto-selected');
check($b->kind==='tenant' && $b->tenantId()===2,'email login selects correct account');
rejects(fn()=>$auth->switchTenant($a,2,$aSession),'unassigned tenant switch denied');
rejects(fn()=>$auth->login('tenant','legacy','shared-secret','test'),'legacy tenant login contract disabled');
$code=$admin->inviteUser($b,'user');
check(sql('SELECT token_hash FROM tenant_invitations')->fetchColumn()===hash('sha256',$code),'only hashed invitation stored');
check($invites->accept($a,strtoupper($code))===2,'existing account explicitly accepts invitation');
rejects(fn()=>$invites->accept($a,$code),'invitation is single-use');
$multi=$auth->login('account','same@example.test','shared-secret','test'); $chooser=$auth->actor($multi);
check($chooser->kind==='account' && count($auth->memberships($chooser))===2,'multiple memberships require selection after authentication');
rejects(fn()=>$chooser->documentScope(),'chooser has no document scope');
$inB=$auth->switchTenant($chooser,2,$multi); $bUser=$auth->actor($inB);
check($bUser->row['role']==='user' && $bUser->accountId()===$a->accountId() && $bUser->id()!==$a->id(),'shared identity with independent membership and role');
check(!$bUser->canAccess(['tenant_id'=>2,'owner_id'=>$b->id()]),'role from Alpha does not leak into Beta');
rejects(fn()=>$admin->users($bUser),'Alpha admin remains ordinary user in Beta');
rejects(fn()=>$admin->inviteUser($bUser,'admin'),'regular user cannot invite admins');
rejects(fn()=>$admin->resetPassword($a,$a->id(),1,'reset-secret'),'tenant admin cannot reset shared password');
$again=$auth->switchTenant($bUser,1,$inB);
check($again['context_token']!==$inB['context_token'],'tenant switch rotates context token');
$version=(int)$bUser->row['auth_version'];
$admin->updateUser($b,$bUser->id(),$version,'Disabled here','user',false);
check($auth->actor($inB)->kind==='account','membership revocation drops only selected context');
check($auth->actor($aSession)->kind==='tenant','membership suspension leaves other tenant session valid');
check(count($auth->memberships($auth->actor($multi)))===1,'disabled membership excluded from choices');
$blockedCode=$admin->inviteUser($b,'admin');
rejects(fn()=>$invites->accept($a,$blockedCode),'invitation cannot bypass existing suspended membership');
$admin->updateUser($b,$bUser->id(),$version+1,'Back','user',true);
check($auth->actor($inB)->kind==='account','reactivation cannot revive old membership context');
$changed=$auth->changePassword($a,'shared-secret','new-shared-secret');
check($auth->actor($aSession)===null && $auth->actor($inB)===null,'shared password change revokes all account sessions');
check($auth->actor($opSession)!==null,'shared password change does not affect operator');
check($auth->actor($bSession)!==null,'shared password change does not affect unrelated account');
rejects(fn()=>$admin->createUser($a,['login'=>'stale','name'=>'Stale','email'=>'stale@example.test','password'=>'secret6'],'user'),'global password change blocks stale admin writes');
$a=$auth->actor($auth->switchTenant($auth->actor($changed),1,$changed));
rejects(fn()=>$admin->createUser($a,['login'=>'new','name'=>'New','email'=>'beta@example.test','password'=>'secret6'],'user'),'existing email is not merged on account creation');
rejects(fn()=>$admin->createUser($a,['login'=>'beta@example.test','name'=>'New','email'=>'new@example.test','password'=>'secret6'],'user'),'username cannot claim another account email');
check((int)sql('SELECT COUNT(*) FROM accounts')->fetchColumn()===2,'failed creations rolled back fully');
$newTenant=$admin->createTenant($operator,'Gamma','',['existing_login'=>'legacy']);
check((int)sql('SELECT COUNT(*) FROM accounts')->fetchColumn()===2 && count($auth->memberships($a))===3,'operator explicitly assigns existing first admin without new account');
$expired=$admin->inviteUser($a,'user'); sql('UPDATE tenant_invitations SET expires_at=UTC_TIMESTAMP()-INTERVAL 1 DAY WHERE token_hash=?',[hash('sha256',$expired)]);
rejects(fn()=>$invites->accept($b,$expired),'expired invitation rejected');
$revoked=$admin->inviteUser($a,'user');
$admin->updateUser($a,$a->id(),(int)$a->row['auth_version'],'Changed admin','admin',true);
rejects(fn()=>$invites->accept($b,$revoked),'creator authorization version change revokes old invitations');
rejects(fn()=>$invites->accept($operator,$blockedCode),'operator cannot acquire membership through user invitation');
check(!str_contains((string)sql("SELECT GROUP_CONCAT(COALESCE(details_json,'')) FROM audit_events")->fetchColumn(),$code),'invitation token not audited in plaintext');
echo "$checks shared-account checks passed.\n";
