<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
use O8\Inbound\AiBookingProposal;
$mapper=new AiBookingProposal(); $checks=0;
function check(bool $ok,string $label):void { global $checks; if(!$ok)throw new RuntimeException($label); $checks++; echo "PASS $label\n"; }
$invoice=['currency'=>'EUR','net'=>'','taxes'=>[],'accountId'=>''];
$catalogue=['vatRates'=>['7','19'],'accounts'=>[['id'=>3,'code'=>'4900']]];
$result=$mapper->prepare($invoice,['netto'=>'100.0000','mwst'=>'19,00','brutto'=>119],$catalogue,[['konto'=>'4900']]);
check($result['invoiceAvailable'] && $result['invoiceWarning']==='' && $result['invoice']['net']==='100.00','valid AI booking is automatically available with normalized monetary values');
check($result['invoice']['taxes']===[['rate'=>'19','amount'=>'19.00']] && $result['invoice']['accountId']==='3','configured rate and exact known account are reused');
$result=$mapper->prepare($invoice,['netto'=>'100','mwst'=>'13','brutto'=>'113'],$catalogue);
check($result['invoiceWarning']!=='' && $result['invoice']['taxes'][0]['rate']==='','mixed or unknown VAT requires correction, never discards the tax amount');
$result=$mapper->prepare($invoice,['netto'=>'100','mwst'=>'19','brutto'=>'120'],$catalogue);
check($result['invoiceWarning']!=='','inconsistent gross total requires correction');
$result=$mapper->prepare($invoice,['netto'=>'100','brutto'=>'119'],$catalogue);
check($result['invoice']['taxes'][0]['amount']==='19.00','missing tax can be derived exactly from net and gross');
$result=$mapper->prepare($invoice,['mwst'=>'19','brutto'=>'119'],$catalogue);
check($result['invoice']['net']==='100.00','missing net can be derived exactly from gross and tax');
$result=$mapper->prepare($invoice,['brutto'=>'119'],$catalogue);
check($result['invoiceAvailable'] && $result['invoiceWarning']!=='' && $result['invoice']['net']==='','gross alone must not silently become net');
$result=$mapper->prepare($invoice,[],$catalogue);
check(!$result['invoiceAvailable'],'no AI amounts leaves booking optional');
$result=$mapper->prepare($invoice,['netto'=>'100','mwst'=>'0','brutto'=>'100'],$catalogue,[['konto'=>'unknown']]);
check($result['invoice']['taxes']===[] && $result['invoice']['accountId']==='','zero tax does not invent a rate or unknown account');
$result=$mapper->prepare($invoice,['netto'=>'-100','mwst'=>'-19','brutto'=>'-119'],$catalogue);
check($result['invoice']['taxes'][0]['rate']==='19' && $result['invoiceWarning']==='','negative credit note amounts remain valid');
$result=$mapper->prepare($invoice,['netto'=>['bad'],'mwst'=>'19','brutto'=>'nonsense'],$catalogue);
check($result['invoiceWarning']!=='','malformed AI values stay incomplete instead of throwing');
$result=$mapper->prepare($invoice,['brutto'=>'119','mwstsatz'=>'19 %'],$catalogue);
check($result['invoice']['net']==='100.00' && $result['invoice']['taxes'][0]['amount']==='19.00' && $result['invoiceWarning']==='','gross and explicit rate derive net and tax');
check($result['bookingTotals']===['net'=>'100.00','tax'=>'19.00','gross'=>'119.00'] && $result['bookingDerived']===['net'=>true,'tax'=>true,'gross'=>false],'overview receives calculated totals with field provenance');
$result=$mapper->prepare($invoice,['netto'=>'100','steuersatz'=>'7'],$catalogue);
check($result['invoice']['taxes'][0]['amount']==='7.00' && $result['invoiceWarning']==='','net and explicit rate derive tax and gross');
$result=$mapper->prepare($invoice,['mwst'=>'19','mwst_satz'=>'19'],$catalogue);
check($result['invoice']['net']==='100.00' && $result['invoiceWarning']==='','tax and explicit nonzero rate derive net and gross');
$result=$mapper->prepare($invoice,['brutto'=>'119','mwstsatz'=>'18'],$catalogue);
check($result['invoiceWarning']!=='','inactive explicit rate cannot be used');
$result=$mapper->prepare($invoice,['netto'=>'100','mwst'=>'7','mwstsatz'=>'19'],$catalogue);
check($result['invoiceWarning']!=='','explicit rate contradicting amount cannot be used');
$result=$mapper->prepare($invoice,['netto'=>'1.000,00','brutto'=>'1.190,00'],$catalogue);
check($result['invoice']['net']==='1000.00' && $result['invoice']['taxes'][0]['amount']==='190.00','unambiguous German grouping is supported');
$result=$mapper->prepare($invoice,['netto'=>'100','mwst'=>'18.99','brutto'=>'118.99'],$catalogue);
check($result['invoice']['taxes'][0]['rate']==='19' && $result['invoice']['taxes'][0]['amount']==='18.99' && $result['invoiceWarning']==='','unique one-cent line-rounding difference preserves reported tax');
$result=$mapper->prepare($invoice,['netto'=>'100','mwst'=>'18.97','brutto'=>'118.97'],$catalogue);
check($result['invoiceWarning']!=='','larger rounding differences remain blocked');
$result=$mapper->prepare($invoice,['steuern'=>[['netto'=>'100','mwstsatz'=>'19'],['brutto'=>'107','mwstsatz'=>'7']]],$catalogue);
check($result['invoiceAvailable'] && $result['invoice']['net']==='200.00' && $result['invoice']['taxes']===[['rate'=>'19','amount'=>'19.00'],['rate'=>'7','amount'=>'7.00']] && $result['invoiceWarning']==='','explicit mixed-rate breakdown derives full invoice totals');
$result=$mapper->prepare($invoice,['brutto'=>'999','steuern'=>[['netto'=>'100','mwstsatz'=>'19'],['netto'=>'100','mwstsatz'=>'7']]],$catalogue);
check($result['invoiceWarning']!=='','breakdown cannot overwrite conflicting provided totals');
echo "$checks AI booking proposal checks passed.\n";
