CREATE TABLE IF NOT EXISTS inbound_items (
    tenant_id BIGINT UNSIGNED NOT NULL,
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    source_item_id BIGINT UNSIGNED NOT NULL,
    owner_id BIGINT UNSIGNED NOT NULL,
    original_name VARCHAR(768) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    state VARCHAR(24) NOT NULL DEFAULT 'pending',
    inventory_status VARCHAR(24) NOT NULL DEFAULT 'pending',
    ai_status VARCHAR(24) NOT NULL DEFAULT 'not_requested',
    has_text_sidecar BOOLEAN NOT NULL DEFAULT FALSE,
    has_json_sidecar BOOLEAN NOT NULL DEFAULT FALSE,
    json_valid BOOLEAN NOT NULL DEFAULT FALSE,
    error_code VARCHAR(64) NULL,
    revision INT UNSIGNED NOT NULL DEFAULT 1,
    discovered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    completed_at DATETIME NULL,
    UNIQUE KEY inbound_item_source (tenant_id, source_item_id),
    UNIQUE KEY inbound_items_tenant_id (tenant_id, id),
    INDEX inbound_owner_state (tenant_id, owner_id, state, updated_at),
    INDEX inbound_ai_state (tenant_id, ai_status, updated_at),
    FOREIGN KEY (tenant_id, source_item_id) REFERENCES source_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, owner_id) REFERENCES users(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS inbound_ai_runs (
    tenant_id BIGINT UNSIGNED NOT NULL,
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    inbound_item_id BIGINT UNSIGNED NOT NULL,
    requested_by BIGINT UNSIGNED NOT NULL,
    origin VARCHAR(24) NOT NULL,
    status VARCHAR(24) NOT NULL,
    result_json JSON NULL,
    error_code VARCHAR(64) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    UNIQUE KEY inbound_ai_runs_tenant_id (tenant_id, id),
    INDEX inbound_ai_item (tenant_id, inbound_item_id, created_at),
    FOREIGN KEY (tenant_id, inbound_item_id) REFERENCES inbound_items(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, requested_by) REFERENCES users(tenant_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
