<?php $acceptanceDocuments=new \O8\Documents\Documents($db,$root); $acceptanceFolders=$acceptanceDocuments->folders($actor); $acceptanceTags=$acceptanceDocuments->tags($actor); ?>
<script type="module" src="<?= h($publicPath) ?>/assets/js/source-acceptance.js?v=<?= h(filemtime($root.'/public/assets/js/source-acceptance.js')) ?>"></script>
<section class="account-sources mt-4" aria-labelledby="sourceSettingsTitle">
<div class="tenant-section-heading"><div><h4 class="h6 mb-1" id="sourceSettingsTitle">Meine Eingangsquellen</h4><p class="mb-0">Persönliche IMAP- und WebDAV-Quellen dieses Mandanten. Zugangsdaten werden verschlüsselt gespeichert und niemals wieder angezeigt.</p></div><span class="tenant-count"><?= count($importSources) ?> Quellen</span></div>
<?php $automaticSources=array_filter($importSources,static fn(array $source):bool=>(bool)$source['enabled'] && (int)$source['interval_minutes']>0); if ($automaticSources && !$sourceWorkerActive): ?>
<div class="alert alert-warning" role="alert"><strong>Automatischer Quellenabruf noch nicht aktiv.</strong><br>Mindestens eine aktive Quelle verwendet ein Intervall größer 0. Dafür muss der Server regelmäßig folgenden Befehl ausführen:<br><code>cd <?= h($root) ?> &amp;&amp; O8_SOURCE_WORKER=1 php bin/source-fetch.php work --once</code><br><span class="small">Empfehlung: einmal pro Minute per Cron. Sobald der Worker ausgeführt wurde, verschwindet dieser Hinweis automatisch. Quellen mit Intervall 0 werden direkt manuell abgerufen und benötigen diesen Cronjob nicht.</span></div>
<?php endif ?>
<?php foreach ($importSources as $source): $cfg=$source['config']; $prefix='source-'.$source['id']; ?>
<details class="source-card o8-info-group o8-info-group--head mb-3"><summary><strong><?= h($source['name']) ?></strong><span class="badge text-bg-secondary ms-2"><?= $source['kind']==='imap'?'IMAP':'WebDAV' ?></span><span class="small text-secondary ms-2"><?= $source['enabled']?'aktiv':'inaktiv' ?></span></summary>
<form method="post" class="row g-3 mt-1"><?php postFields('source_save','account'); ?><input type="hidden" name="id" value="<?= h($source['id']) ?>"><input type="hidden" name="revision" value="<?= h($source['revision']) ?>"><input type="hidden" name="kind" value="<?= h($source['kind']) ?>">
<div class="col-md-6"><label class="form-label d-block">Name<input class="form-control" name="source_name" maxlength="190" required value="<?= h($source['name']) ?>"></label></div>
<div class="col-md-3"><label class="form-label d-block">Intervall (Minuten)<input class="form-control" name="interval" type="number" min="0" max="1440" required value="<?= h($source['interval_minutes']) ?>"><span class="form-text">0 = nur manuell, sonst 5–1440</span></label></div>
<div class="col-md-3"><label class="form-label d-block">KI-Verarbeitung<select class="form-select" name="ai_mode"><?php foreach (['off'=>'Nicht verwenden','manual'=>'Manuell im Eingang','automatic'=>'Nach Abruf automatisch'] as $value=>$label): ?><option value="<?= h($value) ?>" <?= ($cfg['ai_mode']??'manual')===$value?'selected':'' ?>><?= h($label) ?></option><?php endforeach ?></select></label></div>
<?php if ($source['kind']==='imap'): ?>
<div class="col-md-6"><label class="form-label d-block">IMAP-Server<input class="form-control" name="host" maxlength="253" required value="<?= h($cfg['host']??'') ?>"></label></div><div class="col-md-2"><label class="form-label d-block">Port<input class="form-control" name="port" type="number" min="1" max="65535" required value="<?= h($cfg['port']??993) ?>"></label></div><div class="col-md-4"><label class="form-label d-block">Transport<select class="form-select" name="security"><option value="tls" <?= ($cfg['security']??'tls')==='tls'?'selected':'' ?>>TLS direkt</option><option value="starttls" <?= ($cfg['security']??'')==='starttls'?'selected':'' ?>>STARTTLS verpflichtend</option></select></label></div>
<div class="col-md-6"><label class="form-label d-block">Benutzername<input class="form-control" name="username" maxlength="255" required value="<?= h($cfg['username']??'') ?>"></label></div><div class="col-md-6"><label class="form-label d-block">Postfachordner<input class="form-control" name="folder" maxlength="768" required value="<?= h($cfg['folder']??'INBOX') ?>"></label></div>
<?php else: ?>
<div class="col-12"><label class="form-label d-block">WebDAV-HTTPS-Adresse<input class="form-control" name="url" type="url" maxlength="768" required value="<?= h($cfg['url']??'') ?>"></label></div><div class="col-md-8"><label class="form-label d-block">Benutzername<input class="form-control" name="username" maxlength="255" required value="<?= h($cfg['username']??'') ?>"></label></div><div class="col-md-4 form-check-wrap"><label class="form-check-label"><input class="form-check-input" type="checkbox" name="recursive" value="1" <?= !empty($cfg['recursive'])?'checked':'' ?>> Unterordner einbeziehen</label></div>
<?php endif ?>
<div class="col-md-8"><label class="form-label d-block">Passwort / App-Token<input class="form-control" name="source_secret" type="password" maxlength="8192" autocomplete="new-password" placeholder="Gesetzt – leer lassen, um es beizubehalten"></label></div>
<div class="col-md-4 form-check-wrap"><label class="form-check-label"><input class="form-check-input" type="checkbox" name="enabled" value="1" <?= $source['enabled']?'checked':'' ?>> Quelle aktiv</label></div>
<div class="col-12 source-options o8-info-group o8-info-group--soft"><label class="form-check-label"><input class="form-check-input" type="checkbox" name="delete_after" value="1" <?= !empty($cfg['delete_after_fetch'])?'checked':'' ?>> Erfolgreich abgerufene <?= $source['kind']==='imap'?'Nachrichten':'Dateien' ?> an der Quelle löschen</label><p class="small text-secondary mb-0">Die spätere Löschung erfolgt erst nach vollständig verifiziertem Abruf; Löschen im o8-Eingang löscht niemals automatisch an der Quelle.</p></div>
<?php require __DIR__.'/source-acceptance.php'; ?>
<div class="col-12"><button class="btn btn-primary">Quelle speichern</button></div></form>
<form method="post" class="d-inline-block mt-3 me-2"><?php postFields('source_test','account'); ?><input type="hidden" name="id" value="<?= h($source['id']) ?>"><button class="btn btn-surface" type="submit">Verbindung prüfen</button></form>
<form method="post" class="source-delete mt-3"><?php postFields('source_delete','account'); ?><input type="hidden" name="id" value="<?= h($source['id']) ?>"><input type="hidden" name="revision" value="<?= h($source['revision']) ?>"><label class="form-check-label me-2"><input class="form-check-input" type="checkbox" name="confirm" value="yes" required> Löschen bestätigen</label><button class="btn btn-outline-danger" <?= (int)$source['item_count']>0?'disabled title="Bereits verwendete Quelle nur deaktivieren"':'' ?>>Quelle löschen</button></form>
</details>
<?php endforeach ?>
<div class="row g-3">
<div class="col-lg-6"><details class="source-card source-create o8-info-group o8-info-group--soft"><summary><strong>Mailbox hinzufügen</strong></summary><form method="post" class="row g-3 mt-1"><?php postFields('source_save','account'); ?><input type="hidden" name="kind" value="imap"><input type="hidden" name="id" value="0"><input type="hidden" name="revision" value="0">
<div class="col-12"><label class="form-label d-block">Name<input class="form-control" name="source_name" maxlength="190" required></label></div><div class="col-8"><label class="form-label d-block">IMAP-Server<input class="form-control" name="host" maxlength="253" required></label></div><div class="col-4"><label class="form-label d-block">Port<input class="form-control" name="port" type="number" min="1" max="65535" value="993" required></label></div><div class="col-12"><label class="form-label d-block">Transport<select class="form-select" name="security"><option value="tls">TLS direkt</option><option value="starttls">STARTTLS verpflichtend</option></select></label></div><div class="col-12"><label class="form-label d-block">Benutzername<input class="form-control" name="username" maxlength="255" required></label></div><div class="col-12"><label class="form-label d-block">Postfachordner<input class="form-control" name="folder" maxlength="768" value="INBOX" required></label></div><div class="col-12"><label class="form-label d-block">Passwort / App-Token<input class="form-control" name="source_secret" type="password" maxlength="8192" autocomplete="new-password" required></label></div><div class="col-6"><label class="form-label d-block">Intervall<input class="form-control" name="interval" type="number" min="0" max="1440" value="15" required><span class="form-text">0 = nur manuell, sonst 5–1440</span></label></div><div class="col-6"><label class="form-label d-block">KI<select class="form-select" name="ai_mode"><option value="manual">Manuell</option><option value="automatic">Automatisch</option><option value="off">Nicht verwenden</option></select></label></div><div class="col-12 source-options"><label class="form-check-label d-block"><input class="form-check-input" type="checkbox" name="enabled" value="1"> Quelle sofort aktivieren</label><label class="form-check-label d-block mt-2"><input class="form-check-input" type="checkbox" name="delete_after" value="1"> Erfolgreich abgerufene Nachrichten an der Quelle löschen</label></div><div class="col-12"><button class="btn btn-primary">Mailbox speichern</button></div></form></details></div>
<div class="col-lg-6"><details class="source-card source-create o8-info-group o8-info-group--soft"><summary><strong>WebDAV hinzufügen</strong></summary><form method="post" class="row g-3 mt-1"><?php postFields('source_save','account'); ?><input type="hidden" name="kind" value="webdav"><input type="hidden" name="id" value="0"><input type="hidden" name="revision" value="0">
<div class="col-12"><label class="form-label d-block">Name<input class="form-control" name="source_name" maxlength="190" required></label></div><div class="col-12"><label class="form-label d-block">WebDAV-HTTPS-Adresse<input class="form-control" name="url" type="url" maxlength="768" required></label></div><div class="col-12"><label class="form-label d-block">Benutzername<input class="form-control" name="username" maxlength="255" required></label></div><div class="col-12"><label class="form-label d-block">Passwort / App-Token<input class="form-control" name="source_secret" type="password" maxlength="8192" autocomplete="new-password" required></label></div><div class="col-6"><label class="form-label d-block">Intervall<input class="form-control" name="interval" type="number" min="0" max="1440" value="15" required><span class="form-text">0 = nur manuell, sonst 5–1440</span></label></div><div class="col-6"><label class="form-label d-block">KI<select class="form-select" name="ai_mode"><option value="manual">Manuell</option><option value="automatic">Automatisch</option><option value="off">Nicht verwenden</option></select></label></div><div class="col-12 source-options"><label class="form-check-label d-block"><input class="form-check-input" type="checkbox" name="recursive" value="1"> Unterordner einbeziehen</label><label class="form-check-label d-block mt-2"><input class="form-check-input" type="checkbox" name="enabled" value="1"> Quelle sofort aktivieren</label><label class="form-check-label d-block mt-2"><input class="form-check-input" type="checkbox" name="delete_after" value="1"> Erfolgreich abgerufene Dateien an der Quelle löschen</label></div><div class="col-12"><button class="btn btn-primary">WebDAV speichern</button></div></form></details></div>
</div>
</section>
<?php if ($actor->row['role']==='admin'): ?>
<section class="account-sources mt-4" aria-labelledby="aiSettingsTitle">
<div class="tenant-section-heading"><div><h4 class="h6 mb-1" id="aiSettingsTitle">Externe KI-Verarbeitung</h4><p class="mb-0">Mandantenweite, optionale Analyse für Dokumente im Eingang. Ergebnisse bleiben Vorschläge; unbekannte Tags werden niemals angelegt.</p></div><span class="tenant-count"><?= $aiConfiguration['enabled']?'aktiv':'inaktiv' ?></span></div>
<?php $automaticAiSources=array_filter($importSources,static fn(array $source):bool=>(bool)$source['enabled'] && ($source['config']['ai_mode']??'manual')==='automatic'); if ($aiConfiguration['enabled'] && $automaticAiSources && !$aiWorkerActive): ?><div class="alert alert-warning" role="alert"><strong>KI-Hintergrundworker für automatische Verarbeitung noch nicht aktiv.</strong><br>Nur für Quellen mit KI-Modus „Automatisch“ muss der Server regelmäßig folgenden Befehl ausführen:<br><code>cd <?= h($root) ?> &amp;&amp; O8_AI_WORKER=1 php bin/inbound-ai.php work --once</code><br><span class="small">Manuell im Eingang gestartete Analysen werden direkt aus der Oberfläche schrittweise ausgeführt und benötigen keinen Cronjob.</span></div><?php endif ?>
<form method="post" id="aiModelsRefreshForm"><?php postFields('ai_models_refresh','account'); ?></form>
<form method="post" class="row g-3 source-card o8-info-group o8-info-group--head p-3"><?php postFields('ai_configuration_save','account'); ?><input type="hidden" name="revision" value="<?= h($aiConfiguration['revision']) ?>">
<div class="col-12"><label class="form-check-label"><input class="form-check-input" type="checkbox" name="enabled" value="1" <?= $aiConfiguration['enabled']?'checked':'' ?>> Externe KI-Verarbeitung aktivieren</label></div>
<div class="col-12"><label class="form-check-label"><input class="form-check-input" type="checkbox" name="external_processing_confirmed" value="1" <?= $aiConfiguration['external_processing_confirmed']?'checked':'' ?>> Ich bestätige, dass Dokumentinhalte an den konfigurierten externen Dienst übertragen werden dürfen.</label></div>
<div class="col-12"><label class="form-label d-block">OpenAI-kompatibler HTTPS-Endpunkt<input class="form-control" type="url" name="endpoint" maxlength="768" required value="<?= h($aiConfiguration['endpoint']) ?>"></label></div>
<input type="hidden" name="fallback_model" value=""><div class="col-12"><label class="form-label d-block" for="aiPrimaryModel">IONOS-Modell</label><div class="input-group"><select class="form-select" id="aiPrimaryModel" name="primary_model" required><?php $modelOptions=$aiModels?:[$aiConfiguration['primary_model']]; if (!in_array($aiConfiguration['primary_model'],$modelOptions,true)) array_unshift($modelOptions,$aiConfiguration['primary_model']); foreach ($modelOptions as $model): ?><option value="<?= h($model) ?>" <?= $model===$aiConfiguration['primary_model']?'selected':'' ?>><?= h($model) ?></option><?php endforeach ?></select><button class="btn btn-surface" type="submit" form="aiModelsRefreshForm">Aktuelle IONOS-Modelle laden</button></div><span class="form-text"><?= $aiModels?'Aktuelle Liste wurde geladen. Gewünschtes Modell auswählen und anschließend die KI-Konfiguration speichern.':'Der Abruf verwendet die bereits gespeicherte URL und das gespeicherte API-Token.' ?></span></div>
<div class="col-md-8"><label class="form-label d-block">API-Token<input class="form-control" type="password" name="ai_secret" maxlength="8192" autocomplete="new-password" placeholder="<?= $aiConfiguration['secret_set']?'Gesetzt – leer lassen, um es beizubehalten':'Noch nicht gesetzt' ?>"></label></div><div class="col-md-4"><label class="form-label d-block">Timeout je Modell (Sekunden)<input class="form-control" type="number" name="timeout_seconds" min="10" max="300" required value="<?= h($aiConfiguration['timeout_seconds']) ?>"><span class="form-text">Für große Modelle werden mindestens 120 Sekunden empfohlen.</span></label></div>
<div class="col-12"><label class="form-label d-block">Analyseanweisung<textarea class="form-control" name="instruction_text" rows="12" maxlength="50000" required><?= h($aiConfiguration['instruction_text']) ?></textarea><span class="form-text"><code>{{TEXT}}</code> ist Pflicht; <code>{{TAGS}}</code>, <code>{{ACCOUNTS}}</code> und <code>{{VAT_RATES}}</code> werden serverseitig aus den aktiven Katalogen eingesetzt.</span></label></div>
<div class="col-12"><button class="btn btn-primary">KI-Konfiguration speichern</button></div></form>
</section>
<?php endif ?>
